## action.yml
## https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
---

name: 'Ansible'
description: 'Ansible for GitHub Workflows'
inputs:
  vault_password:
    description: Ansible Vault Password
    required: false
    default: ""

  playbook:
    description: Ansible Playbook
    required: true

  action:
    description: Action (validata)
    required: true
    default: "validate"

runs:
  using: 'docker'
  image: 'docker.pkg.github.com/action-ansible/ansible'
  args:
    - ${{ inputs.action }}
